### ISSUE TITLE
Invalid BASE_URI in the version 0.3.0

### ISSUE THREAD

**Issue by superh2m** [MoovOne/timekit-php-sdk#4]
Hello @VaN-dev 
I notice that you add a constant called `BASE_URI` where you specify the api uri of Timekit, you just add an extra "/" at the end : 
`public const BASE_URI = 'https://api.timekit.io/v2/';` to `public const BASE_URI = 'https://api.timekit.io/v2';`

**Comment by VaN-dev** [comment]
fixed by https://github.com/MoovOne/timekit-php-sdk/commit/5832fd4f55a4842824b19c5ea078d1f38abf8565
